[package]
name = "rust_ffi"
version = "0.1.0"
authors = ["Daniel Rivas <ers.daniel+dev@gmail.com>"]
build = "build.rs"

[lib]
name = "sort"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
